# Generated by Django 4.2.7 on 2024-02-25 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='amounts_of_students',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='average_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
